name: flutter_pangle_ads
description: FlutterAds 一款优质的 Flutter 广告插件（字节跳动、穿山甲）
version: 3.1.0
homepage: https://flutterads.top
repository: https://github.com/FlutterAds/flutter_pangle_ads
issue_tracker: https://github.com/FlutterAds/flutter_pangle_ads/issues
documentation: https://github.com/FlutterAds/flutter_pangle_ads/wiki
topics: [flutterads, ads, pangle, bytedance, income]
funding: [https://github.com/FlutterAds/.github]

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.zero.flutter_pangle_ads
        pluginClass: FlutterPangleAdsPlugin
      ios:
        pluginClass: FlutterPangleAdsPlugin
