name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.PUB_OAUTH_ACCESS_TOKEN }}
          flutter_package: true
          skip_test: false
          dry_run: false
      - name: Upload to Pgyer
      # Build apk.
      - run: cd example && flutter build apk
      #  Upload to Pgyer
      - run: curl -F 'file=@example/build/app/outputs/apk/release/app-release.apk' -F '_api_key=${{ secrets.PGYER_API_KEY }}' https://www.pgyer.com/apiv2/app/upload
